Support custom selectors
Mellanox/k8s-rdma-shared-dev-plugin pull request #19
Opened 2020-09-08 17:16 UTC by Mmduh-483

Deprecate field "devices" and support new field "selectors" which provide more flexibility in filtering devices

2020-09-08 17:17 UTC, Mmduh-483 commented
@adrianchiris

2020-09-21 10:53 UTC, moshe010 requested changes
you need to https://github.com/intel/sriov-network-device-plugin/blob/master/images/Dockerfile#L15 to the image

2020-09-21 14:53 UTC, AbdYsn commented
/retest

2020-09-22 05:09 UTC, moshe010 commented
@AbdYsn  why srio_cni_ci is running here?
@Mmduh-483 can you add Fixes #18

2020-09-22 12:10 UTC, AbdYsn commented
> @AbdYsn why srio_cni_ci is running here?
@moshe010 the job configuration were not updated until yesterday, to remove the failing context, we either need a new update of the PR, or i can change it manually to be passing.

2020-09-22 12:50 UTC, Mmduh-483 commented
> @AbdYsn why srio_cni_ci is running here?
> @Mmduh-483 can you add Fixes #18

Added

2020-09-22 14:25 UTC, adrianchiris requested changes
Overall i think this looks good !

I have reviewed this commit by commit so perhaps some of the comments are not relevant for later changes.

Also please update README with a new section about device plugin configuration, explaining the config parameters and a subsection for the various selectors added.

2020-09-22 14:25 UTC, adrianchiris commented on pkg/resources/device_selectors.go
> +type deviceSelector struct {
name is kinda generic as everything here is a device selector

perhaps: `deviceIDSelector` ?

2020-09-22 14:25 UTC, adrianchiris commented on pkg/resources/pci_net_device.go
> +	deviceCode string
deviceID ?

2020-09-22 14:25 UTC, adrianchiris commented on pkg/resources/pci_net_device.go
> +func (nd *pciNetDevice) GetDeviceCode() string {
GetDeviceID ?

2020-09-22 14:25 UTC, adrianchiris commented on pkg/types/types.go
> +	GetDeviceCode() string
GetDeviceID() ?

2020-09-22 14:25 UTC, adrianchiris commented on pkg/utils/utils.go
> +func GetNetDevDriver(pciAddr string) (string, error) {
it will work for any pci device right ? not just netdev

perhaps rename to: `GetPCIDevDriver`

2020-09-22 14:25 UTC, adrianchiris commented on pkg/resources/network_link_manager.go
> +
can you call the file `netlink_manager.go` ? shorter :)

2020-09-22 14:25 UTC, adrianchiris commented on images/k8s-rdma-shared-dev-plugin-config-map.yaml
> +             "selectors": {
can you change to the equivalent to what was here before ? (i.e use ifNames selector)

2020-09-23 06:24 UTC, Mmduh-483 commented on pkg/resources/resources_manager.go
> +	pci, err := ghw.PCI()
ghw.PCI() returns a struct not an interface

2020-09-23 08:43 UTC, Mmduh-483 commented on pkg/resources/server_test.go
> +			deviceList := []types.PciNetDevice{fakePciDevice}
Moved back to the previous commit

2020-09-23 08:58 UTC, Mmduh-483 commented on pkg/resources/resources_manager_test.go
> +		It("Config confusion between \"selector\" and \"devices\"", func() {
There case for each now, mismatch config when both devices and selectors exits and when both are missing

2020-09-23 08:58 UTC, Mmduh-483 commented on pkg/resources/resources_manager_test.go
> +			Expect(len(filteredDevices)).To(Equal(2))
added

2020-09-23 08:59 UTC, Mmduh-483 commented on pkg/resources/resources_manager_test.go
>  			rm := &resourceManager{}
added

2020-09-23 09:00 UTC, Mmduh-483 commented on pkg/types/types.go
> +type Selector struct {
renamed, yes will contain all selectors

2020-09-27 10:24 UTC, adrianchiris requested changes

2020-09-27 10:24 UTC, adrianchiris commented on README.md
> +`"resourceList"` should contain a list of config objects. Each config object may consist of following fields:
is it resouceList or configList ?

2020-09-27 10:24 UTC, adrianchiris commented on README.md
> +| "rdmaHcaMax"   | Y        | Maximum number of RDMA resources that can be provided by the device plugin                                        | Integer       | 1000
> by the device plugin

by the device or by the device plugin resource choose one :)

2020-09-27 10:24 UTC, adrianchiris commented on README.md
> +Note: Although "selectors" and "devices" are not required one and only one of them is a must, it is recommended to use the "selectors", on the other hand the "devices" filed is there only for backpor
> __Note__: Either `selectors` or `devices` must be specified for a given resource.

2020-09-27 10:24 UTC, adrianchiris commented on README.md
> +
you can remove one newline IMO+

2020-09-27 10:24 UTC, adrianchiris commented on README.md
> +| "devices"      | N        | A list of devices names to be selected, same like selectors' ifNames, check the selectors section                 | `string` list | ["ib0", "ib1"]
> A list of devices names to be selected, same like selectors' ifNames, check the selectors section

A list of device names to be selected. same as `ifNames` selector.

2020-09-27 10:24 UTC, adrianchiris commented on README.md
> +| "selectors"    | N        | A map of device selectors for filtering the devices                                                               | json object   | selectors": {"vendors": ["15b3"],"dev
> A map of device selectors for filtering the devices

A map of device selectors for filtering the devices. refer to (Device Selectors)[add link] section for more information

2020-09-27 10:24 UTC, adrianchiris commented on README.md
> +| "deviceIDs" | Target devices' device Hex code as string                      | `string` list | "devices": ["1017"]      |
devices' -> device's ?

2020-09-27 10:24 UTC, adrianchiris commented on README.md
> +
lets add a section about the matching/selection process.

2020-09-27 10:24 UTC, adrianchiris commented on README.md
> +3. Check the new labels added to the node
why is that 3 ? should be 2 right ?

2020-09-27 10:24 UTC, adrianchiris commented on pkg/resources/resources_manager.go
> +	pci, err := ghw.PCI()
ok

2020-09-27 12:08 UTC, adrianchiris commented on README.md
> +The device plugin filters the host devices based on the provided selectors, if there are any missing selectors, the device plugin ignores them. The devices that match all the provided selectors will
what happens if more than one string is provided to each selector ? 
logical *OR* is performed between elements of a specific selector and logical *AND* is performed between selectors.

you covered this in the design doc IIRC

2020-09-28 16:28 UTC, moshe010 approved these changes

2020-09-28 16:28 UTC, merged