Add support for CDI
Mellanox/k8s-rdma-shared-dev-plugin pull request #77
Opened 2023-08-04 09:27 UTC by almaslennikov

https://github.com/container-orchestrated-devices/container-device-interface

2023-08-04 09:27 UTC, almaslennikov commented on images/cdi/k8s-rdma-shared-dev-plugin-cdi-ds.yaml
> +        - image: ghcr.io/mellanox/k8s-rdma-shared-dev-plugin:latest-amd64
This line is dependent on another opened PR: https://github.com/Mellanox/k8s-rdma-shared-dev-plugin/pull/75

2023-08-04 10:07 UTC, almaslennikov commented
@abdallahyas We don't have any copyrights in the repo, should we copyright all files or drop the check?

2023-08-05 12:12 UTC, abdallahyas commented
> @abdallahyas We don't have any copyrights in the repo, should we copyright all files or drop the check?

@almaslennikov we can not drop because it is the company policy, so we can copy the copy right message from any other project and add it to only the newly added files. The CI will only check newly added files, and would ignore the modified files

2023-08-15 11:07 UTC, e0ne requested changes

2023-08-15 11:07 UTC, e0ne commented on cmd/k8s-rdma-shared-dp/main.go
> +		log.Printf("CDI enabled")
log.Printf => log.Println

2023-08-15 11:07 UTC, e0ne commented on pkg/cdi/cdi.go
> +	log.Printf("Created CDI annotations: %v", annotations)
plese, start log messages with lower-case letter

2023-08-16 06:56 UTC, almaslennikov commented
@e0ne addressed your comments and rebased the PR, PTAL

2023-08-16 07:36 UTC, e0ne approved these changes
LGTM. thanks for addressing my comments

2023-08-17 10:30 UTC, adrianchiris reviewed
Hey @almaslennikov appologies for the delayed review !

2023-08-17 10:30 UTC, adrianchiris commented on pkg/cdi/cdi.go
> +	devicesIDs []string, resourceNamePrefix, resourceKind string) (map[string]string, error) {
fail if deviceIDs is empty ?

2023-08-17 10:30 UTC, adrianchiris commented on pkg/cdi/cdi_test.go
> +var _ = Describe("Cdi", func() {
can you test CreateCDISpec() ?

2023-08-17 10:30 UTC, adrianchiris commented on pkg/cdi/cdi_test.go
> +		It("should not fail on non-existing device", func() {
what is the difference between this test case and the first one ?

2023-08-17 10:30 UTC, adrianchiris commented on pkg/resources/server.go
> +	cdiResourceKind = "net-rdma"
nit: net-shared-rdma ?

2023-08-17 10:30 UTC, adrianchiris commented on pkg/resources/server.go
> +	err := rs.updateCDISpec()
why do you prefer to create the spec here an not on allocate when required ?

2023-08-17 10:30 UTC, adrianchiris commented on pkg/resources/server.go
> +			err := rs.updateCDISpec()
if you do it here, you need to protect using rs.mutex like done in rs.sendDevices()

2023-08-17 10:30 UTC, adrianchiris commented on pkg/resources/server.go
> +		log.Printf("initServers(): error creating CDI spec: %v", err)
this is called within ListAndWatch ... log msg is missleading

2023-08-17 10:30 UTC, adrianchiris commented on pkg/resources/server_test.go
> +			obj, err := newResourceServer(conf, fakeDeviceList, true, "socket", false)
lets add tests for:

1. ListAndWatch changes
2. Allocate changes

2023-08-17 10:59 UTC, adrianchiris commented
i have deployed the changes, something is off with the cdi spec, expect further feedback :)

2023-08-20 14:45 UTC, adrianchiris commented on pkg/resources/server.go
> +	err := rs.updateCDISpec()
thinking on it, i think its fine to keep it here. that is, CDI spec generation is performed in listAndWatch

2023-08-20 15:03 UTC, adrianchiris commented
I have deployed device plugin in cdi mode.

the cdi specification generated is as follows:

```
cdiVersion: 0.5.0
containerEdits: {}
devices:
- containerEdits:
    deviceNodes:
    - hostPath: /dev/infiniband/issm0
      path: /dev/infiniband/issm0
      permissions: rw
    - hostPath: /dev/infiniband/umad0
      path: /dev/infiniband/umad0
      permissions: rw
    - hostPath: /dev/infiniband/uverbs0
      path: /dev/infiniband/uverbs0
      permissions: rw
    - hostPath: /dev/infiniband/rdma_cm
      path: /dev/infiniband/rdma_cm
      permissions: rw
    - hostPath: /dev/infiniband/issm1
      path: /dev/infiniband/issm1
      permissions: rw
    - hostPath: /dev/infiniband/umad1
      path: /dev/infiniband/umad1
      permissions: rw
    - hostPath: /dev/infiniband/uverbs1
      path: /dev/infiniband/uverbs1
      permissions: rw
    - hostPath: /dev/infiniband/rdma_cm
      path: /dev/infiniband/rdma_cm
      permissions: rw
  name: "0"
- containerEdits:
    deviceNodes:
    - hostPath: /dev/infiniband/issm0
      path: /dev/infiniband/issm0
      permissions: rw
    - hostPath: /dev/infiniband/umad0
      path: /dev/infiniband/umad0
      permissions: rw
    - hostPath: /dev/infiniband/uverbs0
      path: /dev/infiniband/uverbs0
      permissions: rw
    - hostPath: /dev/infiniband/rdma_cm
      path: /dev/infiniband/rdma_cm
      permissions: rw
    - hostPath: /dev/infiniband/issm1
      path: /dev/infiniband/issm1
      permissions: rw
    - hostPath: /dev/infiniband/umad1
      path: /dev/infiniband/umad1
      permissions: rw
    - hostPath: /dev/infiniband/uverbs1
      path: /dev/infiniband/uverbs1
      permissions: rw
    - hostPath: /dev/infiniband/rdma_cm
      path: /dev/infiniband/rdma_cm
      permissions: rw
  name: "1"
kind: rdma/net-rdma
```
the list of devices goes on up until `rdmaHcaMax` num is reached.

A couple of comments on this one:

1. the device kind is composed of vendor prefix and device class. in our case we should use `nvidia.com` as vendor prefix.
for now as hardcoded value, and later on it may be configurable if desired. current vendor prefix, `rdma` which is what we have hardcoded as resource prefix in device plugin does not really fit in CDI kind. device class `net-rdma` fits well.

2. devices here are eventually PCI devices. so i think CDI device spec should reflect the actual device, its name should be the PCI device address. having duplicate devices (notice also there is duplicate mounts per device) here does not make much sense since eventually we can provide the same CDI device name in multiple device plugin Allocate calls. that means, we would a CDI device per PCI device selected. on Allocate call we may return either one or multiple annotations pointing to one or several CDI devices depending on the actual devices that are part of the pool.

4. current code does not support more than one resource pool since you are writing to the same file `/var/run/cdi/rdma.yaml`


example of a cdi spec file as i envision it:

```
cdiVersion: 0.5.0
containerEdits: {}
devices:
- containerEdits:
    deviceNodes:
    - hostPath: /dev/infiniband/issm0
      path: /dev/infiniband/issm0
      permissions: rw
    - hostPath: /dev/infiniband/umad0
      path: /dev/infiniband/umad0
      permissions: rw
    - hostPath: /dev/infiniband/uverbs0
      path: /dev/infiniband/uverbs0
      permissions: rw
    - hostPath: /dev/infiniband/rdma_cm
      path: /dev/infiniband/rdma_cm
      permissions: rw
  name: "0000:03:00.0"
- containerEdits:
    deviceNodes:
    - hostPath: /dev/infiniband/issm1
      path: /dev/infiniband/issm1
      permissions: rw
    - hostPath: /dev/infiniband/umad1
      path: /dev/infiniband/umad1
      permissions: rw
    - hostPath: /dev/infiniband/uverbs1
      path: /dev/infiniband/uverbs1
      permissions: rw
    - hostPath: /dev/infiniband/rdma_cm
      path: /dev/infiniband/rdma_cm
      permissions: rw
  name: "0000:03:00.1"
kind: nvidia.com/net-rdma
```

2023-08-20 15:10 UTC, adrianchiris commented on pkg/resources/server.go
> +	resourcePrefix string
you may have the same resource prefix for multiple resource servers

2023-09-06 11:00 UTC, adrianchiris requested changes

2023-09-06 11:05 UTC, e0ne commented on pkg/resources/server.go
> +func (rs *resourceServer) updateCDISpec() error {
looks like so. we need to find a way to resolve this issue.

Maybe we can create spec files with a prefix (e.g. `rdma-shared-dp-<pool-name>.yaml`) and delete all these files in the begining of `updateCDISpec`

2023-09-06 11:13 UTC, adrianchiris commented on pkg/resources/server.go
> +func (rs *resourceServer) updateCDISpec() error {
also there is the question of what happens if we change the devices of an existing resource pool, will it replace or just append, i didnt check this.

2023-09-12 08:12 UTC, almaslennikov commented on pkg/resources/server.go
> +func (rs *resourceServer) updateCDISpec() error {
When we change the resource pool, the new spec overwrites the previous one, so we don't need to handle this case explicitly. I added a cleanup call when starting the resource servers to account for the case when the previous instance of device plugin finished unsuccessfully

2023-09-18 07:53 UTC, e0ne requested changes

2023-09-18 07:53 UTC, e0ne commented on pkg/cdi/cdi.go
> +type Impl struct {
let's make this structure private

2023-09-20 13:30 UTC, e0ne requested changes

2023-09-20 13:30 UTC, e0ne commented on deployment/k8s/overlay/cdi.yaml
> +            - name: default-cdi
no need to mount `/etc/cdi`

2023-09-21 13:02 UTC, e0ne approved these changes

2023-09-26 07:40 UTC, merged